### ISSUE TITLE
Add dedicated Review Page for Ice Cream Products

### ISSUE THREAD

**Issue by Vishwajeet594** [dohinaf/basic-icecream-website#102]
### Description: 
**We need to add a new Review Page where customers can submit and read reviews about our ice cream products. This page will allow users to share their feedback, rate the ice creams they’ve tried, and view other customers' opinions. The review page should be consistent with the overall theme of the website (ice cream selling) and visually engaging.**
### Create a dedicated page (/reviews) for customer reviews.
**The page design should match the theme of the ice cream shop (bright, fun, ice-cream-themed colors and graphics).
Include a prominent section for customer-written reviews along with their ratings (using a 5-star rating system).**

**1. Add a review submission form at the top or side of the page with fields for:
2. Name (optional)
3. Review text
4. Star rating (1-5 stars)
5. Select a specific ice cream flavor (dropdown).
6. Include pagination if the number of reviews grows large.**
### please assign this issue to me

**Comment by dohinafs** [comment]
#3 addresses these issues. You can elaborate if you intended something different.

**Comment by Vishwajeet594** [comment]
**Sorry for inconvenience,by mistake I was not look for that I will let u soon with new issue**
