### ISSUE TITLE
Refactor JS: Split large JS into modular components for improved maintainability

### ISSUE THREAD

**Issue by Lonwwolf14** [dohinaf/basic-icecream-website#106]
Our current JavaScript file has grown to nearly 1000 lines, making it difficult to maintain and navigate. To improve code organization, readability, and maintainability, we should consider splitting this large file into smaller, more focused modules.

### Proposed changes:

- Implement a main script file that imports these modular files.
- Update the HTML to reference only the main script file.

### This refactoring will:

- Enhance code organization and readability.
- Improve maintainability by separating concerns.
- Make it easier for developers to locate and modify specific functionalities.
- Potentially improve performance through better caching of individual script files.

**Comment by Rashmi885** [comment]
Hello, I am contributing for the first time to GSSOC, pls assign this issue to me under GSSOC

**Comment by Lonwwolf14** [comment]
@dohinafs pls assign me this issue to 
All the contributors are contributing in the same file and it's hard for other dev's to add more feat.
