### ISSUE TITLE
Enhance Cart Functionality: Fix Total Calculation & Improve Code Readability

### ISSUE THREAD

**Issue by harshpareshbhaigosalya** [dohinaf/basic-icecream-website#107]
While implementing the cart functionality in the shopping application, I've encountered an issue with the total calculation displayed in the cart. The total price shows $20 instead of the correct amount of $15.99 for the selected items. This issue requires immediate attention to ensure accurate cart totals and enhance user experience.

Changes Made:
Updated Total Calculation Logic:-
Modified the displayCart() function to calculate the total based on the prices of items currently in the cart, ensuring that the correct total is displayed.
Ensured that when items are added to the cart, their prices contribute accurately to the total displayed.

Improved Code Readability:-
Added comments throughout the JavaScript code to clarify the purpose of various functions and blocks, making it easier for future developers to understand the logic.
Enhanced variable naming for better clarity where needed.

Steps to Reproduce:-
Add items to the cart.
Observe the total displayed in the cart.
Note the discrepancy between the expected total and the displayed total.

Expected Result:-
The total amount in the cart should accurately reflect the sum of the individual item prices, correctly displaying $15.99 instead of $20.

It is crucial to test the updated code thoroughly to confirm that the total calculation is consistent across different scenarios (adding/removing items).
Please ensure that the changes maintain the existing functionality without introducing any new issues.

Hey @dohinafs, Please review the changes, implement the fix, and add the tags hacktoberfest-accepted and girlscript-summer-of-code-2024-extended to this issue.

Tags: hacktoberfest-accepted, girlscript-summer-of-code-2024-extended
Thank you for your attention to this matter!

![Screenshot 2024-10-03 094701](https://github.com/user-attachments/assets/8ecb11b9-e52a-42f4-9cac-d9f0a2e9df2f)
![Screenshot 2024-10-03 100114](https://github.com/user-attachments/assets/3d0d5b1b-0930-4026-98cf-c98ed4354581)

**Comment by Riddhi12349** [comment]
hi please assign me this issue
