### ISSUE TITLE
Change Twitter Symbol to X in footer section

### ISSUE THREAD

**Issue by kundana29** [dohinaf/basic-icecream-website#109]
I would like to propose a change to update the Twitter symbol to "X" in to reflect Twitter's recent rebranding. This change ensures consistency with the platform's new identity and avoids any potential confusion for users. please assign this issue to me

![Screenshot 2024-10-03 120905](https://github.com/user-attachments/assets/94369f9f-b035-4aee-a88e-b924625b85b9)

**Comment by dohinafs** [comment]
This change has already been implemented in https://arcticdelights.netlify.app/
