### ISSUE TITLE
Add to Wishlist button text is difficult to notice due to color scheme

### ISSUE THREAD

**Issue by prashikk** [dohinaf/basic-icecream-website#111]
The "Add to Wishlist" button on the website currently has a white background and the text inside the button is of a similar shade of white. This makes the button text difficult to notice, especially for users who are quickly browsing the page or have visual impairments.

Expected behavior: The button text should have a contrasting color to make it easily noticeable and readable. This could be achieved by changing either the background or the text color.

Screenshots : 
<img width="565" alt="Screenshot 2024-10-03 at 12 18 38 PM" src="https://github.com/user-attachments/assets/39ab2e2b-bf3b-4be6-8e4e-0f10bb824dbd">

Suggested solution: Consider changing the button text to a darker color or changing the button's background color to provide better contrast.

Additional context: I would love to work on this issue as this will be my first contribution in GSSoC extended event.

**Comment by prashikk** [comment]
Hey @dohinafs, I noticed that I was assigned this issue and had worked on it, creating a pull request as well (please check #127). However, I saw that @Naga-Himaja also made another pull request, which got merged. I was under the impression that contributions are handled on a first-come, first-served basis, and that only the assigned contributor should work on an issue. Could you please clarify if that's the case? I just want to make sure I understand the process correctly.

**Comment by dohinafs** [comment]
@prashikk Hey, I've merged your PR. Sorry for the inconvenience as it is difficult for me to keep track of the issues as there are many created, so I think I assigned it to the other contributor too by accident.
