### ISSUE TITLE
improve the page

### ISSUE THREAD

**Issue by Roopalgn** [dohinaf/basic-icecream-website#12]
Hey i checked out your website and felt that the colours ,buttons and background didnt match the vibe of a site selling delicious and colourful ice creams. With the knowledge of frontend ,i feel like i can make your website eye catching.Can you please assign this issue to me?along with the relevant tags

**Comment by dohinafs** [comment]
@Roopalgn You have been assigned.

**Comment by rounakdey6** [comment]
i want to change the navbar section and the pages structure , want to add a slide format for ice-cream to attract the users, please assign this issue to me

**Comment by rohitsharma2610** [comment]
hey can you assign me, i have much experience in front-end development.

**Comment by dohinafs** [comment]
@rounakdey6 @rohitsharma2610 Kindly raise your issues separately in a new thread so I can assign it to you.
