### ISSUE TITLE
Problem regarding the number of icecream in cart 

### ISSUE THREAD

**Issue by CoolCoder431** [dohinaf/basic-icecream-website#133]
<img width="525" alt="Screenshot 2024-10-03 at 6 30 28 PM" src="https://github.com/user-attachments/assets/0471b750-307c-45fe-a809-2c96af0fb915">
It is not analysing that the same ice cream is added multiple times, it should only increase the number of that ice cream but currently it is adding another ice cream with its proper name as there was no ice cream with that name before that needs to be resolved and I am willing to do that if you assign me this problem

**Comment by AnklekarMahima** [comment]
@dohinafs I would like to work on this problem.
Please assign me this issue with labels hacktoberfest and gssoc-24 extd #
