### ISSUE TITLE
proper spacing in header

### ISSUE THREAD

**Issue by kashishchadha** [dohinaf/basic-icecream-website#138]
proper spacing in nav bar is required i can do this please assign this to me i will do this

**Comment by ishanguptaofficial** [comment]
Hello Dohinaf Team,

My name is Ishan, and I am a 4th-year BTech student with experience in full-stack development. I would love to contribute to your project. Here is my LinkedIn profile: https://www.linkedin.com/in/ishanguptaofficial/.

Could you please assign me to this issue? Looking forward to your response.

Best regards,
Ishan
