### ISSUE TITLE
TOGGLE SWITCH INSTEAD OF BUTTON

### ISSUE THREAD

**Issue by STDYGIT** [dohinaf/basic-icecream-website#139]
Button gives an old look to the website here is a switch which adds a cool animaiton in changing your website
![Screenshot 2024-10-02 at 12 44 47 PM](https://github.com/user-attachments/assets/52bf8836-7f2e-45e2-abb2-bf73658a12ff)
![Screenshot 2024-10-02 at 12 44 31 PM](https://github.com/user-attachments/assets/2fb4392f-25da-4efe-a524-ec72ddceb275)

**Comment by STDYGIT** [comment]
hey sir @dohinafs 
I would like to update your website using these cool switch instead of button

**Comment by Riddhi12349** [comment]
hi please assign me this issue
