### ISSUE TITLE
Update Twitter button as X

### ISSUE THREAD

**Issue by poorvikaa08** [dohinaf/basic-icecream-website#14]
The current display button for Twitter on the website still shows the old Twitter bird icon. Twitter has rebranded to "X" with a new logo, so this button should be updated to reflect the latest branding.

Screenshot 📸 

![image](https://github.com/user-attachments/assets/2d391464-40ad-4301-a970-403bdf803887)

I would like to work on this issue under GSSoC24 and Hactoberfest
@dohinafs Would you assign it to me, Thankyou

**Comment by AhanaGanguly965** [comment]
can u assign this project to me?

**Comment by harish08102004** [comment]
Hey If this isn't closed I can work on this.
