### ISSUE TITLE
Bad Responsivness

### ISSUE THREAD

**Issue by prvn-kumar01** [dohinaf/basic-icecream-website#148]
https://github.com/user-attachments/assets/b5b6dfc9-7fa6-4daf-a00a-f78a6782f2b5

There is responsivness issue , while shrinking webpage the navbar elements disappear
I can fix this issue in better way .

**Comment by prvn-kumar01** [comment]
hey @dohinafs 
 Kindly assign me I can fix it

**Comment by pallaviii21** [comment]
@dohinafs assign me this issue I can fix it easily in minimum time
