### ISSUE TITLE
Issue - Same pricing of icecreams

### ISSUE THREAD

**Issue by poorvikaa08** [dohinaf/basic-icecream-website#151]
All the creams listed in the menu section have the same pricing

It would have been better if the pricing was done according to the flavours.
I would like to fix this.
@dohinafs Would u assign this issue under gssoc and hacktoberfest with the appropriate level?

Screenshots 📸 
![image](https://github.com/user-attachments/assets/5c206b35-b4aa-4164-afe8-1a1d6c87742c)
![image](https://github.com/user-attachments/assets/947b9017-e822-4fac-b859-87e70ed28151)

Thank you.

**Comment by poorvikaa08** [comment]
@dohinafs Can you add the appropriate level label?

**Comment by SHUBHAG100520** [comment]
i can also work on it .can you assign it to me.

**Comment by viraljain7** [comment]
plz assign it to me. i want to work on it

**Comment by poorvikaa08** [comment]
I fixed this issue; it's in PR. 
Once approved, it's resolved
