### ISSUE TITLE
menu card hover fixing

### ISSUE THREAD

**Issue by riyarane46** [dohinaf/basic-icecream-website#156]
@dohinafs , 
the menu cards when hovered over decrease in size, but i believe that the cards should always enlarge a bit instead . 
Many modern websites use enlargement on hover to create a sense of depth and interactivity.
When users hover over menu cards, an enlargement effect feels natural, guiding their attention to specific options without overwhelming the layout. Shrinking, on the other hand, might feel counterintuitive and diminish the focus on the item.

could you please assign me this task under GSSoC24 extd and hactoberfest24.

https://github.com/user-attachments/assets/2591c44b-3cec-4b99-8525-ff8de4f4eb74

**Comment by riyarane46** [comment]
@dohinafs can you please also assign the level label to this issue

**Comment by riyarane46** [comment]
@dohinafs , 
i actually have a problem can you please help me 
i have contributed to your project and you have merged 3 of my PR 
issue - #65 , #155 , #156 
and its been quite long since you merged them but they are not visible on my leaderboard and its important for me to get these points 

is there anything that you can do to resolve this please . it would be great help

**Comment by dohinafs** [comment]
Many contributors are facing this issue. I have followed gssoc guidelines and added the labels appropriately so even I'm not sure about why this issue is occurring.
