### ISSUE TITLE
Implement new design for the website

### ISSUE THREAD

**Issue by dohinafs** [dohinaf/basic-icecream-website#163]
Anyone interested in working on a new design for the website is welcome to comment below. It can be any theme or color based (light/dark) as per your interest. 

You can provide a prototype for your design first before working on it. 

Here is a sample design provided by AyushiTaralkar  :
https://www.figma.com/design/IHfxqnqSuxIe3tQHVgE5O1/Untitled?node-id=0-1&node-type=canvas

**Comment by poorvikaa08** [comment]
@dohinafs I would like to work on this.

**Comment by karthik-kiran-29** [comment]
I can create a new design and did a little market research so my design will be colorful, simple and direct the user to order something. I have choosed this color palette.
![image](https://github.com/user-attachments/assets/bd8e97a0-02c6-4062-9ee1-476e8439a217)
If you assign this to me I will create a design and get your feedback, Once your okay with it.I can develop the page-Thank you.

**Comment by AyushiTaralkar** [comment]
> Anyone interested in working on a new design for the website is welcome to comment below. It can be any theme or color based (light/dark) as per your interest.
> 
> You can provide a prototype for your design first before working on it.
> 
> Here is a sample design provided by AyushiTaralkar : https://www.figma.com/design/IHfxqnqSuxIe3tQHVgE5O1/Untitled?node-id=0-1&node-type=canvas

I can make other pages too for you. Did you like the theme n design?

**Comment by dohinafs** [comment]
Yes, you can collaborate if needed.

**Comment by AyushiTaralkar** [comment]
okay I will design other (about, review, contact) pages also using this theme (light theme). Maybe other collaborators can work on dark theme by then.

**Comment by poorvikaa08** [comment]
@AyushiTaralkar Would you like to colllaborate with me?

**Comment by karthik-kiran-29** [comment]
I would like to code the designs that you make,If that is okay and help in designing.Can you please create a discord or something?

**Comment by poorvikaa08** [comment]
I will re-design the home page

**Comment by AyushiTaralkar** [comment]
> I would like to code the designs that you make,If that is okay and help in designing.Can you please create a discord or something?

It would be great if you could code.

**Comment by AyushiTaralkar** [comment]
I have never created one yet : | (DISCORD)

**Comment by poorvikaa08** [comment]
You can join this discord channel
https://discord.gg/6AJVHY7q

**Comment by AyushiTaralkar** [comment]
For dark theme will we need new designs? then maybe @poorvikaa08 can make the home page as you want .
@karthik-kiran-29 pls let me know will we require different designs for light n dark themes?

**Comment by AyushiTaralkar** [comment]
New design for 'About us ' page is ready hope @dohinafs  you like it....


![Screenshot 2024-10-04 161842](https://github.com/user-attachments/assets/9fddb7d5-a1e6-4866-9a1c-a23ade7d8305)

**Comment by AyushiTaralkar** [comment]
If you want any changes feel free to let me know....

**Comment by Niharika062004** [comment]
We can make changes to the menu page . Wanted to make it carousel .
![CAROUSEL](https://github.com/user-attachments/assets/dd46caa8-d8b8-45c8-80e6-a9af8801b24e)

It will help in leveraging the visibility of the product.
i would like to contribute to this project, hope youll give me a chance.

**Comment by dohinafs** [comment]
@Niharika062004 Kindly create a separate issue and I'll assign it to you.
