### ISSUE TITLE
Improve footer

### ISSUE THREAD

**Issue by devarsheecodess** [dohinaf/basic-icecream-website#167]
![image](https://github.com/user-attachments/assets/14ae8ca4-ab9f-4098-9f23-5afc7beebcb7)
I want to improve the UI of footer. plz assign me this issue with gssoc-extd label

**Comment by GitNinja36** [comment]
Hello! I'd like to work on improving the footer UI for this issue. Could you please assign it to me with the gssoc-extd label? Looking forward to contributing!

**Comment by devarsheecodess** [comment]
Thank you @dohinafs for assigning this issue, plz also add a level label (like level1,level2,level3) as it was told that level labels must be present
