### ISSUE TITLE
Implementing a login/sign up page 

### ISSUE THREAD

**Issue by Soumya03007** [dohinaf/basic-icecream-website#178]
Adding a login/Sign up page in this website

**Comment by Soumya03007** [comment]
please assign this task me .....

**Comment by ishanguptaofficial** [comment]
Hello Dohinaf Team,

My name is Ishan, and I am a 4th-year BTech student with experience in full-stack development. I would love to contribute to your project. Here is my LinkedIn profile: https://www.linkedin.com/in/ishanguptaofficial/.

Could you please assign me to this issue? Looking forward to your response.

Best regards,
Ishan

**Comment by Riddhi12349** [comment]
hi please assign me this issue
