### ISSUE TITLE
add hover animations to buttons

### ISSUE THREAD

**Issue by devxMani** [dohinaf/basic-icecream-website#18]

**Comment by monishkumardvs** [comment]
i want to work can u assign me

**Comment by dohinafs** [comment]
@devxMani You have been assigned.

**Comment by devxMani** [comment]
This issue is sorted MERGE this PR

**Comment by Riddhi12349** [comment]
hi please assign me this issue

**Comment by devxMani** [comment]
@Riddhi12349 this issue is already done see I have raised a PR
