### ISSUE TITLE
better UI to footer section

### ISSUE THREAD

**Issue by Ishika-Gupta06** [dohinaf/basic-icecream-website#187]
@dohinafs please assign me this task under GSSOC-EXT & HACKTOBERFEST & LEVEL-1,2,3

**Comment by ishanguptaofficial** [comment]
Hello Dohinaf Team,

My name is Ishan, and I am a 4th-year BTech student with experience in full-stack development. I would love to contribute to your project. Here is my LinkedIn profile: https://www.linkedin.com/in/ishanguptaofficial/.

Could you please assign me to this issue? Looking forward to your response.

Best regards,
Ishan
