### ISSUE TITLE
Add a button that brings you back to top of web page 

### ISSUE THREAD

**Issue by Ishika-Gupta06** [dohinaf/basic-icecream-website#188]
@dohinafs assign me this task under GSsoc-ext & hactoberfest & level-1,2,3

**Comment by Smit1610** [comment]
@dohinafs please assign this issue to me with hacktoberfest label

**Comment by ishanguptaofficial** [comment]
Hello Dohinaf Team,

My name is Ishan, and I am a 4th-year BTech student with experience in full-stack development. I would love to contribute to your project. Here is my LinkedIn profile: https://www.linkedin.com/in/ishanguptaofficial/.

Could you please assign me to this issue? Looking forward to your response.

Best regards,
Ishan
