### ISSUE TITLE
Navbar and Logo Alignment Fix Across Screen Sizes.

### ISSUE THREAD

**Issue by sakshikedari** [dohinaf/basic-icecream-website#198]
The navbar and logo have inconsistent spacing across different screen sizes, making the layout look off. The logo should always stay aligned to the left, while the navbar items need to maintain proper spacing on the right, regardless of the screen size. The aim is to ensure both the logo and navbar are well-aligned for a smooth, responsive design.
@dohinafs 
Can you please assign this issue to me? I'd like to work on it.

**Comment by Akanshaku** [comment]
I would like to work on this issue @dohinafs
