### ISSUE TITLE
Add a Feedback Form for User Input

### ISSUE THREAD

**Issue by TBorundia** [dohinaf/basic-icecream-website#2]
Create a feedback form to collect user input and improve website features. The form should include the following:

Input fields for name, email, and feedback message.
A star rating system for user satisfaction.
Form validation to ensure all fields are correctly filled before submission.
A responsive design that works seamlessly on all devices.
A success/failure message after form submission.
Option to customize the appearance of the form to match the website’s theme.

**Comment by Laxmi123-coder** [comment]
please assign it to me i love to contribute in this

**Comment by dohinafs** [comment]
@Laxmi123-coder You have been assigned.

**Comment by TBorundia** [comment]
@dohinafs , But this issue is opened by me. So it must be assigned to me.

**Comment by rounakdey6** [comment]
please assign this issue to me
