### ISSUE TITLE
Add Github Greeting Bot

### ISSUE THREAD

**Issue by KiranBaliga** [dohinaf/basic-icecream-website#20]
Hey 🥳 Looks like an amazing project idea! I see this repo lacks a small enhancement Github Greetings bot that sends auto messages to greet new users when they raise a PR or an issue. Let me know if you would like this level1 set up! Please assign to me if interested! (GSSoC24 Contribution)

**Comment by dohinafs** [comment]
@KiranBaliga You have been assigned.

**Comment by KiranBaliga** [comment]
@Altair-05 @dohinafs Please review the PR and action accordingly. Thank you!
