### ISSUE TITLE
contact us page structure is not good 

### ISSUE THREAD

**Issue by anish013326** [dohinaf/basic-icecream-website#214]
![image](https://github.com/user-attachments/assets/25a35125-5238-41a8-b0a2-5687bf753914)
 navbar hide the contact us page text and i add some good design and make good structure..

**Comment by 01-aniket-maity** [comment]
@dohinafs Please assign me this task of improving the UI of the Contact Us Page under GSSoC and hacktoberfest-accepted tags.

I will improve the layout of the site by fixing the navbar, details section and footer, enhancing the placeholders and making the page responsive accordingly.
