### ISSUE TITLE
Bug while dark mode on Login / sign up button

### ISSUE THREAD

**Issue by prvn-kumar01** [dohinaf/basic-icecream-website#217]
![Screenshot 2024-10-06 103928](https://github.com/user-attachments/assets/1cbed0fb-94cd-4d9e-8ab2-bf05c0cbf2f6)
As you can see in screenshot while dark mode login/signup button disaappear

**Comment by prvn-kumar01** [comment]
Pls make it level 1

**Comment by Riddhi12349** [comment]
hi please assign me this issue

**Comment by prvn-kumar01** [comment]
Assign this issue to @pallaviii21.
I have another work , She can easily solve this problem.
