### ISSUE TITLE
Add Footer to Website

### ISSUE THREAD

**Issue by Abhishek-TG18** [dohinaf/basic-icecream-website#219]
This issue addresses the need for a footer on the website, which is currently missing. A footer is a crucial component of web design that provides essential information and navigational links, enhancing the overall user experience.

The primary objectives of this feature are:

Improved Navigation: Include important links such as "About Us," "Contact," "Privacy Policy," and "Terms of Service" to help users find relevant information easily.

Branding: Reinforce brand identity by including the company logo and any relevant branding elements in the footer.

Contact Information: Provide contact details such as an email address, phone number, or social media links to facilitate user communication and engagement.

Accessibility: Ensure that the footer is designed with accessibility in mind, making it easy for all users to navigate and understand.

Consistent Design: The footer should align with the overall design and color scheme of the website to maintain a cohesive look and feel.

**Comment by vikassahu1** [comment]
Hello, I want to work on this issue please assign it to me under hacktoberfest label.
Thank You!

**Comment by Abhishek-TG18** [comment]
Is your project removed from gssoc-ext
