### ISSUE TITLE
Creating Scroll effects in Home page

### ISSUE THREAD

**Issue by karthik-kiran-29** [dohinaf/basic-icecream-website#228]
![image](https://github.com/user-attachments/assets/829566ff-84d9-4011-b0cc-f41cbbfbdb91)
I can make the left section move with scroll until footer which will improve the design.

**Comment by ishanguptaofficial** [comment]
Hello Dohinaf Team,

My name is Ishan, and I am a 4th-year BTech student with experience in full-stack development. I would love to contribute to your project. Here is my LinkedIn profile: https://www.linkedin.com/in/ishanguptaofficial/.

Could you please assign me to this issue? Looking forward to your response.

Best regards,
Ishan

**Comment by Riddhi12349** [comment]
hi please assign me this issue
