### ISSUE TITLE
Cart Issue

### ISSUE THREAD

**Issue by ABHI-SHEK-001** [dohinaf/basic-icecream-website#229]
when you add any item, there is no pop-up that the item is added or not. also it not showing how many items are there in the cart. i want to solve this issue and add some functionality in it
![Screenshot 2024-10-06 141009](https://github.com/user-attachments/assets/8f06bf99-1a54-413d-be6d-91cdbcfb682f)
![image](https://github.com/user-attachments/assets/925f056a-b8fc-460d-b580-8ce629fc5680)

**Comment by ishanguptaofficial** [comment]
Hello Dohinaf Team,

My name is Ishan, and I am a 4th-year BTech student with experience in full-stack development. I would love to contribute to your project. Here is my LinkedIn profile: https://www.linkedin.com/in/ishanguptaofficial/.

Could you please assign me to this issue? Looking forward to your response.

Best regards,
Ishan

**Comment by Riddhi12349** [comment]
hi please assign me this issue
