### ISSUE TITLE
Build website responsive

### ISSUE THREAD

**Issue by vijaychandra1910** [dohinaf/basic-icecream-website#23]
![Screenshot 2024-10-01 224529](https://github.com/user-attachments/assets/6519dfd9-413c-4d10-836b-9325b69f7f02)
The nav menu option is gone when decreasing the screen size. Also whole website not be responsive. Make website responsive for all devices.

**Comment by Pooja3Bhattrai** [comment]
Hello @dohinafs ,  please assign this issue  to me, i will make it responsive in a efficient manner

**Comment by dohinafs** [comment]
@vijaychandra1910 You're interested in being assigned this issue?

**Comment by vijaychandra1910** [comment]
yeah i will.

**Comment by dohinafs** [comment]
@vijaychandra1910 You have been assigned.

**Comment by vijaychandra1910** [comment]
Completed #153

**Comment by vijaychandra1910** [comment]
complete #153 
![Screenshot 2024-10-04 010959](https://github.com/user-attachments/assets/a52bfadf-f145-43b4-8796-8ce5db14febe)
![Screenshot 2024-10-04 010931](https://github.com/user-attachments/assets/da1b2b2d-c8f1-4c71-aa6a-568f7cc2682d)
![Screenshot 2024-10-04 010943](https://github.com/user-attachments/assets/7ceac376-40d6-40c3-9408-79ea27af8aba)
