### ISSUE TITLE
Login/signup botton not visible in dark mode..

### ISSUE THREAD

**Issue by piyusdev2006** [dohinaf/basic-icecream-website#230]
### I will change the colour of the button .. so it will provides appealing looks in light as well as dark mode..

- Actual Behaviour in Dark Mode 
   
![Screenshot 2024-10-06 145735](https://github.com/user-attachments/assets/93cf754d-a425-41f6-bf71-8990e7a14208)

- Expected Behaviour In both Light/Dark Mode
   
  
![Screenshot 2024-10-06 145919](https://github.com/user-attachments/assets/4d85d9f6-6227-4b24-9227-66675426126d)
![Screenshot 2024-10-06 145937](https://github.com/user-attachments/assets/78cc90b6-66d8-4a48-9dab-e245f6634312)

please assing this issue to me .. i won't let you down 🙌 ..

**Comment by ishanguptaofficial** [comment]
Hello Dohinaf Team,

My name is Ishan, and I am a 4th-year BTech student with experience in full-stack development. I would love to contribute to your project. Here is my LinkedIn profile: https://www.linkedin.com/in/ishanguptaofficial/.

Could you please assign me to this issue? Looking forward to your response.

Best regards,
Ishan
