### ISSUE TITLE
FIXING THE COLOUR COMBINATION AND UI

### ISSUE THREAD

**Issue by RAJIV81205** [dohinaf/basic-icecream-website#231]
YOUR WEBSITE IS NOT MATCHING THE VIBE OF A ICE CREAM , THE COLOR THE PICTURE ARE LOOKING COMPARED TO A ICE CREAM WHICH IS BRIGHT , ASSIGN ME TO FIX IT

**Comment by ishanguptaofficial** [comment]
Hello Dohinaf Team,

My name is Ishan, and I am a 4th-year BTech student with experience in full-stack development. I would love to contribute to your project. Here is my LinkedIn profile: https://www.linkedin.com/in/ishanguptaofficial/.

Could you please assign me to this issue? Looking forward to your response.

Best regards,
Ishan
