### ISSUE TITLE
Enhance Hero text

### ISSUE THREAD

**Issue by subin-shk** [dohinaf/basic-icecream-website#234]
The text in banner or hero of the index page in light mode is not clear. This may be due to similar color in banner image and text color.

Assign this task to me.

![image](https://github.com/user-attachments/assets/527c17f5-0bc4-453f-996f-a3c71ad09af8)

**Comment by ishanguptaofficial** [comment]
Hello Dohinaf Team,

My name is Ishan, and I am a 4th-year BTech student with experience in full-stack development. I would love to contribute to your project. Here is my LinkedIn profile: https://www.linkedin.com/in/ishanguptaofficial/.

Could you please assign me to this issue? Looking forward to your response.

Best regards,
Ishan

**Comment by subin-shk** [comment]
@ishanguptaofficial with a skills like yours, you can surely find other issues to raise.
