### ISSUE TITLE
Improving the alignment and disposition of Login and Signup buttons in home page

### ISSUE THREAD

**Issue by kanduru-abhiram** [dohinaf/basic-icecream-website#235]
Hey @dohinafs,

I just loved the contents in the navbar, but feels a bit of disturbance between login and sign up buttons in the navbar. It can be improved by increasing the padding size of the buttons.

![image](https://github.com/user-attachments/assets/76dc2a43-3376-4f57-9cb9-9735dfe15c35)

Kindly assign me this issue under Hacktoberfest2024.

**Comment by ishanguptaofficial** [comment]
Hello Dohinaf Team,

My name is Ishan, and I am a 4th-year BTech student with experience in full-stack development. I would love to contribute to your project. Here is my LinkedIn profile: https://www.linkedin.com/in/ishanguptaofficial/.

Could you please assign me to this issue? Looking forward to your response.

Best regards,
Ishan
