### ISSUE TITLE
Search Bar styling

### ISSUE THREAD

**Issue by Rohinipilla** [dohinaf/basic-icecream-website#236]
![image](https://github.com/user-attachments/assets/b597ef24-bc99-4e87-b267-bd6d283a63d7)

i want to design the search bar to opened int the header only

**Comment by ishanguptaofficial** [comment]
Hello Dohinaf Team,

My name is Ishan, and I am a 4th-year BTech student with experience in full-stack development. I would love to contribute to your project. Here is my LinkedIn profile: https://www.linkedin.com/in/ishanguptaofficial/.

Could you please assign me to this issue? Looking forward to your response.

Best regards,
Ishan
