### ISSUE TITLE
Enhancing the cards 

### ISSUE THREAD

**Issue by Isabelle36** [dohinaf/basic-icecream-website#238]
The cards are pretty basic right now i can customize them.

**Comment by ishanguptaofficial** [comment]
Hello Dohinaf Team,

My name is Ishan, and I am a 4th-year BTech student with experience in full-stack development. I would love to contribute to your project. Here is my LinkedIn profile: https://www.linkedin.com/in/ishanguptaofficial/.

Could you please assign me to this issue? Looking forward to your response.

Best regards,
Ishan
