### ISSUE TITLE
Increase Engagement And Loading Speed

### ISSUE THREAD

**Issue by Adarsh-Chaubey03** [dohinaf/basic-icecream-website#24]
I find few space of improvement at my first experience after opening the website. Here are some changes i would like to make keeping focus to increase user engagement and loading time

>  Image Management:
         - Remove all externally linked images.
         - Create a dedicated "images" folder to store independent images, enhancing loading speed.

> Layout and Design:
         - Give  background some light - gradient look instead of  solid black
         -  improved CSS for better interactivity.
 
> Cart Button:
            - redirects users to a new page or keeps them on the same page with a proper, responsive layout.

> Search Bar Enhancement:
              - Modify the search bar so that clicking the search button slides results to the left, keeping them within the navigation bar, not below it.

Please assign this task to me under gssoc and hectoberfest. Looking forward to contribute further to this project

**Comment by dohinafs** [comment]
@Adarsh-Chaubey03 You have been assigned for the issue on image management and search bar enhancement. The issues 2 and 3 you have listed have already been put forward previously.

**Comment by Adarsh-Chaubey03** [comment]
> @Adarsh-Chaubey03 You have been assigned for the issue on image management and search bar enhancement. The issues 2 and 3 you have listed have already been put forward previously.

Ok I will be working on 1 and 4.

**Comment by Riddhi12349** [comment]
hi please assign me this issue

**Comment by Adarsh-Chaubey03** [comment]
Hi @Riddhi12349  this issue is quite old, so there’s a lower chance that it will be assigned to you. If you are still interested in working on this section, I can close this issue, and you can create a new one for a better chance of being assigned as I am not working on this issue . However, if you prefer to proceed with this one, it might be helpful to tag (@ dohinafs ) to increase your chances of getting assigned...

**Comment by Riddhi12349** [comment]
Do I can raise issues if I found some problem in them and then work on them
?

**Comment by Adarsh-Chaubey03** [comment]
Yes obviously... You can raise a new issue and once they assign it ..you can start working on it...
