### ISSUE TITLE
Creating Buttons with better contract

### ISSUE THREAD

**Issue by akhil11sharma** [dohinaf/basic-icecream-website#242]
<img width="557" alt="Screenshot 2024-10-06 at 5 00 04 PM" src="https://github.com/user-attachments/assets/9011529e-7ef3-4fc3-abbd-c57e34a3a0aa">

I want to give better colors and to buttons to make it more impressive

**Comment by ishanguptaofficial** [comment]
Hello Dohinaf Team,

My name is Ishan, and I am a 4th-year BTech student with experience in full-stack development. I would love to contribute to your project. Here is my LinkedIn profile: https://www.linkedin.com/in/ishanguptaofficial/.

Could you please assign me to this issue? Looking forward to your response.

Best regards,
Ishan
