### ISSUE TITLE
Adding scroll bar to the wishlist

### ISSUE THREAD

**Issue by richa-k23** [dohinaf/basic-icecream-website#244]
Since there is no scroll bar applied to the wishlist, the user experience diminishes if they add multiple items. 
Therefore, I would like to add a scroll bar to the wishlist for a smoother flow of actions. 

**Image of current wishlist without scrollbar:**
<img width="284" alt="image" src="https://github.com/user-attachments/assets/c06479c6-f332-4684-8454-42f3a466bb19">

**I would like to add a scroll similar to this:**
<img width="56" alt="image" src="https://github.com/user-attachments/assets/57cceff8-cd42-4da8-92a5-b697d3ea24f7">

I have added the scroll bar in the shopping cart in an earlier pull request. The above image is of that. I would also like to style it for both the cart and wishlist so that it matches the overall webpage scrollbar styling.

Could you please assign me this work?

**Comment by ishanguptaofficial** [comment]
Hello Dohinaf Team,

My name is Ishan, and I am a 4th-year BTech student with experience in full-stack development. I would love to contribute to your project. Here is my LinkedIn profile: https://www.linkedin.com/in/ishanguptaofficial/.

Could you please assign me to this issue? Looking forward to your response.

Best regards,
Ishan

**Comment by dohinafs** [comment]
@ishanguptaofficial 
Hello,
Kindly don't comment under other contributor's issues and raise your own issues separately. They should not be duplicate. Only then I will be able to assign it to you.
