### ISSUE TITLE
Making Nav bar a bit less dense

### ISSUE THREAD

**Issue by hritika2409** [dohinaf/basic-icecream-website#246]
<img width="941" alt="image" src="https://github.com/user-attachments/assets/134a9772-6616-4a95-8b67-52924739e23f">

**Comment by AditiKushwaha01** [comment]
I can make it better please assign this issue to me and add labels with levels also.

**Comment by dohinafs** [comment]
@hritika2409 Kindly explain more on how?

**Comment by AditiKushwaha01** [comment]
@hritika2409 do consider me for this
