### ISSUE TITLE
Making Search Bar Responsive

### ISSUE THREAD

**Issue by Akshita246** [dohinaf/basic-icecream-website#247]
The search bar should be responsive so that whatever is search using that a response is generated.
Please assign this to me @dohinafs under GSSOC 24 Extended .

**Comment by ishanguptaofficial** [comment]
Hello Dohinaf Team,

My name is Ishan, and I am a 4th-year BTech student with experience in full-stack development. I would love to contribute to your project. Here is my LinkedIn profile: https://www.linkedin.com/in/ishanguptaofficial/.

Could you please assign me to this issue? Looking forward to your response.

Best regards,
Ishan

**Comment by pameladeysarkar2003** [comment]
please assign me this task i'm confident about fixing the issue @dohinafs
