### ISSUE TITLE
Changing the CSS 

### ISSUE THREAD

**Issue by Akshita246** [dohinaf/basic-icecream-website#248]
The website arctic delights evokes a sense of warmth, creativity, and a delightful ice-cream experience. To fully embody this vision, we need to ensure that our theme reflects these qualities. Please assign this to me @dohinafs

**Comment by ishanguptaofficial** [comment]
Hello Dohinaf Team,

My name is Ishan, and I am a 4th-year BTech student with experience in full-stack development. I would love to contribute to your project. Here is my LinkedIn profile: https://www.linkedin.com/in/ishanguptaofficial/.

Could you please assign me to this issue? Looking forward to your response.

Best regards,
Ishan

**Comment by Akshita246** [comment]
Hi Akshita here actually I already solved the search bar issue but you can
still change the css and whatever issue you feel is there in the code and
as I am not the actual owner i cannot assign this to you but you can commit
changes and pull requests to dohinaf

**Comment by dohinafs** [comment]
@Akshita246 Are you interested in working on this?

**Comment by Akshita246** [comment]
Yes, I'm interested.
