### ISSUE TITLE
Want to update a few features on the home page for more user interaction

### ISSUE THREAD

**Issue by Sneha22072005** [dohinaf/basic-icecream-website#249]
![image](https://github.com/user-attachments/assets/99c60c59-3314-4272-86fd-1f0919cd68e8)
here I'd like to add an eye-catching text first instead of 'Lorem ipsum...' and then I want to do something like this that every 4–5 seconds the image scrolls (right to left) to the next automatically while the page is open.

![image](https://github.com/user-attachments/assets/820a066e-5800-4d7d-951d-00d06f220ac4)
next, when the user hovers on the choice cards on the menu, they become slightly bigger and have a glow effect on the background.

What do you think about this idea? Would you like to assign it to me? @dohinafs

**Comment by ishanguptaofficial** [comment]
Hello Dohinaf Team,

My name is Ishan, and I am a 4th-year BTech student with experience in full-stack development. I would love to contribute to your project. Here is my LinkedIn profile: https://www.linkedin.com/in/ishanguptaofficial/.

Could you please assign me to this issue? Looking forward to your response.

Best regards,
Ishan

**Comment by Sneha22072005** [comment]
@dohinafs

**Comment by dohinafs** [comment]
Kindly look at the current deployments. Your version is older.
