### ISSUE TITLE
want to enhance the footer section as its not visible properly

### ISSUE THREAD

**Issue by jyothimanoj12** [dohinaf/basic-icecream-website#250]
![Screenshot 2024-10-06 194207](https://github.com/user-attachments/assets/4ed67a9d-367c-4583-b002-6da863551f27)

this is how the footer section of the homepage looks like , since its a delicies website , it would look better if we add colors to it etc

can you plz assign me this issue under gsoc extended , hackoberfest-accepted , level 2 tags

**Comment by ishanguptaofficial** [comment]
Hello Dohinaf Team,

My name is Ishan, and I am a 4th-year BTech student with experience in full-stack development. I would love to contribute to your project. Here is my LinkedIn profile: https://www.linkedin.com/in/ishanguptaofficial/.

Could you please assign me to this issue? Looking forward to your response.

Best regards,
Ishan

**Comment by jyothimanoj12** [comment]
> Hello Dohinaf Team,
> 
> My name is Ishan, and I am a 4th-year BTech student with experience in full-stack development. I would love to contribute to your project. Here is my LinkedIn profile: https://www.linkedin.com/in/ishanguptaofficial/.
> 
> Could you please assign me to this issue? Looking forward to your response.
> 
> Best regards, Ishan

i am already working on it , sorry

**Comment by jyothimanoj12** [comment]
@dohinafs Can you assign me to solve this issue under gsoc-ext , level 2 , hacktoberfest-accepted tags

**Comment by jyothimanoj12** [comment]
ASSIGN LEVEL 2 TAG PLZ 

 DONE #308

**Comment by jyothimanoj12** [comment]
Done

**Comment by jyothimanoj12** [comment]
According to gsoc guidelines enhancement of a feature is a level 2 issue
