### ISSUE TITLE
about us and our blogs heading isnt properly visible in light mode

### ISSUE THREAD

**Issue by Codewithmeowmeow** [dohinaf/basic-icecream-website#254]
![WhatsApp Image 2024-10-06 at 8 36 52 PM](https://github.com/user-attachments/assets/921bd30c-050f-4cf8-8238-dab8ef4c04f5)
 As you can see about us and our blogs heading isnt properly visible in light mode
![WhatsApp Image 2024-10-06 at 8 36 59 PM](https://github.com/user-attachments/assets/5e85be04-f873-4e61-9dad-1307f5343250)

**Comment by ishanguptaofficial** [comment]
Hello Dohinaf Team,

My name is Ishan, and I am a 4th-year BTech student with experience in full-stack development. I would love to contribute to your project. Here is my LinkedIn profile: https://www.linkedin.com/in/ishanguptaofficial/.

Could you please assign me to this issue? Looking forward to your response.

Best regards,
Ishan
