### ISSUE TITLE
text written in feedback section is not visible

### ISSUE THREAD

**Issue by Codewithmeowmeow** [dohinaf/basic-icecream-website#255]
![WhatsApp Image 2024-10-06 at 8 42 41 PM](https://github.com/user-attachments/assets/271d2862-b0be-44e8-8e18-9dbc635b08b9)

**Comment by shruti9935** [comment]
Can you assign me this issue under hacktober gssoc ext

**Comment by ishanguptaofficial** [comment]
Hello Dohinaf Team,

My name is Ishan, and I am a 4th-year BTech student with experience in full-stack development. I would love to contribute to your project. Here is my LinkedIn profile: https://www.linkedin.com/in/ishanguptaofficial/.

Could you please assign me to this issue? Looking forward to your response.

Best regards,
Ishan

**Comment by Codewithmeowmeow** [comment]
#255 fixed
