### ISSUE TITLE
footer is not visible in light mode

### ISSUE THREAD

**Issue by Codewithmeowmeow** [dohinaf/basic-icecream-website#256]
![foooooooooooot](https://github.com/user-attachments/assets/52eea917-6b9b-4b1f-b8e6-2ee0851d5b88)

**Comment by ishanguptaofficial** [comment]
Hello Dohinaf Team,

My name is Ishan, and I am a 4th-year BTech student with experience in full-stack development. I would love to contribute to your project. Here is my LinkedIn profile: https://www.linkedin.com/in/ishanguptaofficial/.

Could you please assign me to this issue? Looking forward to your response.

Best regards,
Ishan
