### ISSUE TITLE
Redesign LogIn page 

### ISSUE THREAD

**Issue by HeartTick** [dohinaf/basic-icecream-website#257]
I would like to design again the Login page of the website please assign this task to me.
![image](https://github.com/user-attachments/assets/72b5faaf-02a3-4bb6-8a2f-7c18c34566e2)

**Comment by harbakshsinghbaath** [comment]
Please assign this to me too

**Comment by HeartTick** [comment]
Can u please assign the level tag on this issue.
Thank you
