### ISSUE TITLE
Re Design the SignUp page .

### ISSUE THREAD

**Issue by HeartTick** [dohinaf/basic-icecream-website#258]
I would l like to Redesign the sign up page of your website please assign this task to me.
Thank you.
![image](https://github.com/user-attachments/assets/3e8e9009-cd5f-466c-ad9c-7945472edc25)

**Comment by ishanguptaofficial** [comment]
Hello Dohinaf Team,

My name is Ishan, and I am a 4th-year BTech student with experience in full-stack development. I would love to contribute to your project. Here is my LinkedIn profile: https://www.linkedin.com/in/ishanguptaofficial/.

Could you please assign me to this issue? Looking forward to your response.

Best regards,
Ishan
