### ISSUE TITLE
Adjusting the Position of the Elements in the website.

### ISSUE THREAD

**Issue by HeartTick** [dohinaf/basic-icecream-website#259]
Adjusting the Positions of the Elements in the Blogs section Because those all are to words Right I would like to Re Position the Elements.
![image](https://github.com/user-attachments/assets/4995b70e-b40c-4949-86db-fe14e2354d2f)

**Comment by ishanguptaofficial** [comment]
Hello Dohinaf Team,

My name is Ishan, and I am a 4th-year BTech student with experience in full-stack development. I would love to contribute to your project. Here is my LinkedIn profile: https://www.linkedin.com/in/ishanguptaofficial/.

Could you please assign me to this issue? Looking forward to your response.

Best regards,
Ishan

**Comment by Riddhi12349** [comment]
hi please assign me this issue
