### ISSUE TITLE
add an animation "pan zoom effect" for our item images

### ISSUE THREAD

**Issue by hkcodings** [dohinaf/basic-icecream-website#26]

**Comment by hkcodings** [comment]
![1](https://github.com/user-attachments/assets/eef26d36-8105-4cd2-b7fe-30d364a6cf70)

**Comment by hkcodings** [comment]
Please assign me this issue with GSSOC Ext and hactoberfest label

**Comment by dohinafs** [comment]
@hkcodings You have been assigned.
