### ISSUE TITLE
Adding Rollover Animation to the page 

### ISSUE THREAD

**Issue by aditya07389** [dohinaf/basic-icecream-website#268]
# hey @dohinafs ,
I was checking out your website and its pretty cool but i would like to suggest few changes (U.I and functionality) .
1) Adding roll over animation as you scroll down or scroll up in the website.
p.s. : you can check out this website to see how rollover animation looks like:
https://www.nmit.ac.in/

2) Adding a back to top button which will appear when you have scrolled down completely.

3) setting up localstorage , showing a pop up when an item is added

4) Improving the Overall U.I. of the page by adding few animations

5) showing the number of items in the cart next to the cart symbol
i would love to work on these issues .Kindly assign it to me .
P.S. : Please add the following labels : gssoc extd , hactoberfest and level 3
Thankyou.

**Comment by aditya07389** [comment]
hey thanks for assigning the issue , 
i hope my contribution will be valuable for you

**Comment by sunidhi3** [comment]
Please assign this to me i can work on it I'm a GSSoC contributor

**Comment by aditya07389** [comment]
Pr for this issue has been raised and merged @sunidhi3
