### ISSUE TITLE
Dark Mode: Login/Signup Forms Not Visible

### ISSUE THREAD

**Issue by akhil11sharma** [dohinaf/basic-icecream-website#269]
In the current implementation of the dark mode for the ArticDelights site, the Login and Signup forms are not clearly visible due to low contrast between the background and text/form fields. This makes it difficult for users to interact with these forms when dark mode is enabled.

Steps to reproduce:

Navigate to the Login or Signup page.
Switch to dark mode.
Notice that the form elements (input fields, text, and buttons) are hard to see.
Proposed Solution:
I would like to work on amending the dark mode theme to improve the visibility of the Login and Signup forms. This will involve:

Adjusting the colors of the form backgrounds, input fields, and text to provide better contrast.
Ensuring accessibility standards are met for readability in dark mode.
Let me know if I can proceed with these changes!

**Comment by RitikSinha04** [comment]
you can assign me for this task

**Comment by akhil11sharma** [comment]
i can perform this task way better as i have worked on such projects
