### ISSUE TITLE
Enhance the Contact Us Section for Arctic Delight Website

### ISSUE THREAD

**Issue by 770navyasharma** [dohinaf/basic-icecream-website#270]
Hi, I would like to contribute by enhancing the Contact Us section of the Arctic Delight website. The current section is very basic and can be significantly improved in terms of design and functionality. Below are some of the improvements I propose:

Proposed Enhancements:
Responsive Design: Make the section fully responsive to look great on all devices (mobile, tablet, desktop).
User-Friendly Layout: Revamp the layout to include a more modern, clean design that better aligns with the Arctic Delight brand.
Labels Requested:
Enhancement
UI/UX
Hacktoberfest
GSSoC (GirlScript Summer of Code)
Level 2 or 3
These changes will improve user interaction and accessibility, making it easier for users to contact the website owners. I look forward to contributing and enhancing this section!

<img width="1232" alt="Screenshot 2024-10-07 at 9 04 18 AM" src="https://github.com/user-attachments/assets/3f2b2e92-927b-4c94-82a5-988ec2818e68">

**Comment by Riddhi12349** [comment]
hi please assign me this issue

**Comment by anushkas1704** [comment]
Hi @dohinafs Please assign this issue to me, will redesign the layout to feature a more modern, streamlined look that aligns more effectively with the Arctic Delight brand.

**Comment by anushkas1704** [comment]
Hi @dohinafs Please assign this issue to me, will redesign the layout to feature a more modern, streamlined look that aligns more effectively with the Arctic Delight brand.
