### ISSUE TITLE
Add a footer section in the website

### ISSUE THREAD

**Issue by Akki-58** [dohinaf/basic-icecream-website#28]
Description:
I would like to add a footer to the website that would include 
- links to socials
- links to related sections of the website (such as home, about, menu, etc.)
- and other relevant links.

Kindly assign this issue to me with gssoc-ext label with appropriate level and also hactoberfest-accepted label.

**Comment by dohinafs** [comment]
@Akki-58 This website already has a footer section with links to socials and the header with related sections of the website is dynamic and is visible throughout the website irrespective of scrolling. 
Is there any functionality you're interested in improving in the footer section?
