### ISSUE TITLE
Add an animated contact page

### ISSUE THREAD

**Issue by Astro-Dude** [dohinaf/basic-icecream-website#283]
I will add an animated contact page like the reference I have given below. I will match it to the theme of your website.

https://github.com/user-attachments/assets/0bcad1b2-433d-435c-abbe-f220d668e7ba

**Comment by dohinafs** [comment]
You can make this as a subscription section instead of a contact page.

**Comment by hemant2807** [comment]
i can solve this issue. kindly assign me the issue under gssoc24 extd and hacktoberfes label

**Comment by Astro-Dude** [comment]
I could also make a contact page similar to this, but yes if you want a subscription page then I will get it done as soon as possible.
Thank you so much for assigning me this.

**Comment by hemant2807** [comment]
i am willing to add an animated contact us page
