### ISSUE TITLE
Make the page Responsive and more attractive

### ISSUE THREAD

**Issue by samriddhitiwary** [dohinaf/basic-icecream-website#285]
I would like to make the page responsive and attractive when hovered.
![image](https://github.com/user-attachments/assets/0901c90b-1dc7-48f8-808a-bcdb64058a40)

**Comment by dohinafs** [comment]
Kindly look at the updated version of our website: https://arcticdelights.netlify.app/
May I know from where you viewed the above version?

**Comment by samriddhitiwary** [comment]
@dohinafs I think it was the vercel or Deployment Link

**Comment by dohinafs** [comment]
From the gssoc project platform?

**Comment by samriddhitiwary** [comment]
I am I don't remember properly, but I guess it was from there
