### ISSUE TITLE
Making a better about us page 

### ISSUE THREAD

**Issue by ThunderShadows** [dohinaf/basic-icecream-website#295]
The about us section looks stagnant and the doesn't convey much information of "Arctic Delights" website as well as it's past experiences and so on and about it's history.

@dohinafs 

I wanted to do a page dedicated to About us of the company "Arctic Delights" and make a vision statement and a mission statement about it along with the owners of the company.

![image](https://github.com/user-attachments/assets/51c91faa-f1f4-4ee6-8cbd-6e2ffa8daee1)

![image](https://github.com/user-attachments/assets/af89f575-b1fd-4d06-bb16-3b2cd2c38ea5)

**Comment by AditiKushwaha01** [comment]
Assign this to me and please add labels also

**Comment by Pragya79645** [comment]
Assign this to me, I would like to add certain changes over it.

**Comment by dohinafs** [comment]
@ThunderShadows Are you still working on this issue?

**Comment by ThunderShadows** [comment]
> @ThunderShadows Are you still working on this issue?

Yes. Needs one more day. I shall commit by tomorrow EOD.
