### ISSUE TITLE
Improve the login and sign-in pages

### ISSUE THREAD

**Issue by hana-maria** [dohinaf/basic-icecream-website#297]
Make the ui better with hover animations and effects and overall better layout
This is what it is currently 
<img width="554" alt="Screenshot 2024-10-07 at 11 41 29 PM" src="https://github.com/user-attachments/assets/a6d0bb83-6a53-4131-acd5-ae363840f2a6">

**Comment by aditya07389** [comment]
Hey @dohinafs i could work on this issue , please assign it to me .

Ill make it similar to this :
![image](https://github.com/user-attachments/assets/57a7ae77-0a63-41d3-ad17-5307630c9911)

and signup :

![image](https://github.com/user-attachments/assets/f875c3c1-69be-4d54-acce-eaac7f735a6b)

**Comment by hana-maria** [comment]
@dohinafs will do this tomorrow! busy with exams. sorry for the delay
