### ISSUE TITLE
Add Review Section to Website

### ISSUE THREAD

**Issue by TBorundia** [dohinaf/basic-icecream-website#3]
Implement a "Review" section on the website to display customer feedback and reviews. This section should allow users to read and submit reviews, contributing to the credibility and engagement of the website.

![image](https://github.com/user-attachments/assets/536bf22e-7ab5-4e7c-9eaf-dc6c809f258e)

**Comment by Laxmi123-coder** [comment]
please assign this task to me i love to contribute in this

**Comment by dohinafs** [comment]
@Laxmi123-coder You have been assigned.

**Comment by TBorundia** [comment]
@dohinafs , But this issue is opened by me. So it must be assigned to me.

**Comment by dohinafs** [comment]
@TBorundia 
I'm sorry about this misunderstanding.
As far as I know, issues can be raised and posted by anyone who finds it. Unless you ask me to assign it to you, I cannot. If you wish, I can have you assigned along with the other assignee for level3 issues. Is that alright? 
In the future, kindly mention that you wish to be assigned so that there is no confusion.

**Comment by TBorundia** [comment]
@dohinafs ,  I have also contributed in GSSoC'24.
So  according to that issue must be assigned to who have raised it.
So I request you to please assign it to me and also the other issues I have raised.

**Comment by dohinafs** [comment]
@TBorundia Okay, I understand. I'll assign the issue to you.

**Comment by TBorundia** [comment]
@dohinafs , Thank you so much.
can you also assign issue #1 and #2 to me as they are also raised by me.

**Comment by dohinafs** [comment]
@TBorundia No problem, I have assigned the issues raised by you to you and unassigned the previous contributors. Kindly state your intention to be assigned when you wish to contribute next time to prevent such misunderstandings.

**Comment by TBorundia** [comment]
@dohinafs Okay !!
Thank You for understanding. 
From next time I will also mention that i am interested.

**Comment by Divyansh2992** [comment]
I want to contribute in it,please assign it to me
