### ISSUE TITLE
Changing Various UI inconsistencies

### ISSUE THREAD

**Issue by SagnikGos** [dohinaf/basic-icecream-website#303]
There are various UI issues like-
1) Header elements are uneven and header is very broad.
![header](https://github.com/user-attachments/assets/20345866-4755-4514-95cb-5dc79a714922)
2)when You hover above the chatbot the text goes out of bounds.
![chatbot](https://github.com/user-attachments/assets/e2417702-552a-4f8b-989a-e65dd78d0b2d)
3)booking section is uneven and needs ui changes.
![booking section](https://github.com/user-attachments/assets/20c23b9a-078f-48fc-b294-e2e924d6e0f4)
4)ratings and review section is in white mode even if the page is in dark mode.
![ratings and review](https://github.com/user-attachments/assets/85d4fbb2-3b78-435b-b4d9-621377d6d0b7)

@mdazfar2 please assign me this issue.
I am a GSSOC'24-extd. contributor, hacktoberfest contributor.
thank you!

**Comment by mdazfar2** [comment]
@SagnikGos As of now, we do not need it. We will let you know in the future if there is a need. Please search for another issue and raise it, which I'm happy to assign to you.

- Don't forget to give our repository a star and let me know once you've done it.

**Comment by SagnikGos** [comment]
@mdazfar 2 okay thanks.

**Comment by mdazfar2** [comment]
@SagnikGos - Don't forget to give our repository a star and let me know once you've done it.
