### ISSUE TITLE
Toggle button for small pages

### ISSUE THREAD

**Issue by sayanp607** [dohinaf/basic-icecream-website#305]
![Screenshot 2024-10-08 101147](https://github.com/user-attachments/assets/5a151e05-d4a3-4373-b196-0d20f70c2e97)
The options in the header like home, about , menu etc they are not visible in small pages. Please assign this task to me ,I will add a toggle button where all those options will appear separately and clicking on those options user will be redirected to exact pages.

**Comment by Riddhi12349** [comment]
hi please assign me this issue
