### ISSUE TITLE
"Rearrange Layout: Move Rating Section Above Customer Review Section"

### ISSUE THREAD

**Issue by Ayan-Khan79** [dohinaf/basic-icecream-website#313]
The current layout of the product page has the customer reviews section displayed above the rating section, which may confuse users who expect to rate a product before submitting a review. To improve the user experience, we need to rearrange the layout so that the Rating Section appears above the Customer Review Section.

<img width="767" alt="image" src="https://github.com/user-attachments/assets/cba6e174-a947-4554-9f61-89bc84bfed82">

Task:
Move the rating section to be positioned directly above the customer review section.
Ensure the layout remains responsive across all devices.
Test the flow to verify that users can rate and then write their reviews seamlessly.

Expected Outcome:
The rating section should appear before the customer review section, offering a more intuitive flow for users when interacting with the product review form.

@dohinafs Please assign me this issue under gssco label and hacktoberfest label

**Comment by Riddhi12349** [comment]
hi please assign me this issue

**Comment by dohinafs** [comment]
> hi please assign me this issue

Hi, kindly create a separate issue that has not been raised before and I'll assign it to you.
