### ISSUE TITLE
Signup Page Form

### ISSUE THREAD

**Issue by SumitSahu44** [dohinaf/basic-icecream-website#319]
In Signup form when user enter their name it should  not visible clearly so i can fix it and also design signup page for better experience

https://github.com/user-attachments/assets/7d6fa809-c4a1-425c-8090-2182dd00db49

so assign this to me under gssoc-ext and level labels

**Comment by SumitSahu44** [comment]
hey @dohinafs if it's good then merge it

**Comment by karthikarun063** [comment]
I can fix this assign it to me as well as this will be first contribution

**Comment by dohinafs** [comment]
> I can fix this assign it to me as well as this will be first contribution

Kindly create a separate issue that hasn't been raised before and it will be assigned to you.
