### ISSUE TITLE
Issue Title: "Add 'About Us' Section"

### ISSUE THREAD

**Issue by AswaniBolisetti** [dohinaf/basic-icecream-website#335]
@dohinafs 
Issue Description: The website currently lacks an 'About Us' section. I propose adding this section to share the brand’s mission, values, and commitment to sustainability, helping users understand our story and connect with the brand.

I’d like to work on adding this feature. Please assign this issue to me under gssoc-ext, hacktoberfest-accepted, level

**Comment by Altair-05** [comment]
@AswaniBolisetti  website already has an About Us section
