### ISSUE TITLE
chatbot is not working 

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [dohinaf/basic-icecream-website#341]
i can add a new chatbot which will be fine tuned to this website , @dohinafs can you please assign me this task.

**Comment by Altair-05** [comment]
@T-Rahul-prabhu-38, I’m assigning this issue to you. We will only merge if the new chatbot is better than the current one

**Comment by T-Rahul-prabhu-38** [comment]
sure i can work on that.
what will the level be.

**Comment by Altair-05** [comment]
@T-Rahul-prabhu-38  kindly tag me there

**Comment by T-Rahul-prabhu-38** [comment]
yes ive done it.

**Comment by T-Rahul-prabhu-38** [comment]
@Altair-05 i have tagged u there , please review it.
