### ISSUE TITLE
there is no Ui for signup/login page

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [dohinaf/basic-icecream-website#342]
@dohinafs if you can assign me this ill create a nice Ui for this page.
<img width="592" alt="Screenshot 2024-10-08 at 9 36 03 PM" src="https://github.com/user-attachments/assets/2f58a033-d2ec-4e95-8e25-cf5c70691a7c">

**Comment by T-Rahul-prabhu-38** [comment]
@dohinafs i can improve the UI of the current forms and also organise the files as lot of html files are scattered.

**Comment by dohinafs** [comment]
Will you be implementing login and sign up in a separate page?

**Comment by T-Rahul-prabhu-38** [comment]
i can do that aswell.

**Comment by T-Rahul-prabhu-38** [comment]
i can create 2 seperate pages and add storage features to it.
