### ISSUE TITLE
Change Background Image to an Attractive Ice Cream-Themed Design

### ISSUE THREAD

**Issue by aparna-44** [dohinaf/basic-icecream-website#344]
I propose updating the background image of the  ice cream website to create a more appealing and engaging visual experience for users. An attractive ice cream-related background can enhance the overall aesthetic and reflect the theme of our website.
The existing background image may not adequately represent the ice cream theme.
It lacks visual appeal and does not capture the attention of users.
@dohinafs plz assign me this issue

**Comment by Altair-05** [comment]
@aparna-44, please provide ur ideas . u can also add screenshots. If it looks good, we will assign it to you

**Comment by aparna-44** [comment]
@Altair-05 , @dohinafs 
we can add any of the images given below, see if you like it.
![ice cream3](https://github.com/user-attachments/assets/e210f369-f4d4-48f9-b09d-98e4ecab85c0)
![ice-cream 2](https://github.com/user-attachments/assets/9e14cc4a-9081-4c40-ba1a-6870409ee126)
![ice-cream1](https://github.com/user-attachments/assets/23a39c9b-b1ca-4903-bdba-23852bb6499c)
![icecream4](https://github.com/user-attachments/assets/a45bfb46-0533-403b-86c2-9b4557b3fb0c)
