### ISSUE TITLE
🐞[Bug]:- Blog Page not available 

### ISSUE THREAD

**Issue by iarmaanx** [dohinaf/basic-icecream-website#347]
There is no blog page in the website.

I have my personal [blog website](https://code-better.hashnode.dev/) so I have experience of writing blogs.

I can make a blog page for your website related to Ice cream explaining different flavours of ice cream.

**Comment by Altair-05** [comment]
<img width="847" alt="image" src="https://github.com/user-attachments/assets/26df4cd2-dad0-429f-999a-bcb24b1ea8c3">

@iarmaanx, the blog page is already there; please check
