### ISSUE TITLE
Create Admin (Seller) Page 

### ISSUE THREAD

**Issue by saras-69** [dohinaf/basic-icecream-website#35]
Description:
I would like to implement an Admin (Seller) page and a User page for the application. These pages will provide separate functionalities for sellers and users.

Proposed Solution:

Admin (Seller) Page:

Design a dashboard for sellers to manage their products, view sales analytics, and handle orders.
Include functionality for adding, editing, and deleting products.
Implement order management features (e.g., order status updates, shipment tracking).
User Page:

Create a user-friendly interface for users to browse products, view order history, and manage their profiles.
Include features for searching and filtering products.
Allow users to leave reviews and ratings for products.
Benefits:

Enhances the overall user experience by providing tailored interfaces for sellers and users.
Facilitates better management of products and orders for sellers.
"Please assign this issue to me so that I can work on it."

**Comment by dohinafs** [comment]
@saras-69 You have been assigned.
