### ISSUE TITLE
Our Menu section is not aligned

### ISSUE THREAD

**Issue by akanksha1055** [dohinaf/basic-icecream-website#384]
i will align the OUR MENU section and add animation to the Cards displaying ice creams options on hovering over it

please assign me under :
Hacktober
GSSoC

![image](https://github.com/user-attachments/assets/81b09b75-cf42-4d60-a2ed-30bf622919d2)

**Comment by dohinafs** [comment]
View the current version of the website here:
https://arcticdelights.netlify.app/
