### ISSUE TITLE
Bad resposivness 

### ISSUE THREAD

**Issue by prvn-kumar01** [dohinaf/basic-icecream-website#40]
Uploading artic.mp4…

resposivness error

**Comment by dohinafs** [comment]
@prvn-kumar01 Kindly provide more details about the issue.

**Comment by prvn-kumar01** [comment]
https://github.com/user-attachments/assets/b128be69-60c7-41a3-aed4-f48e80dfc155

As you can see in this video while shrink all head components like home , about etc are disappear 
to solve this we can create a navbar and add these options in navbar while shrinking

**Comment by prvn-kumar01** [comment]
Assign me this problem I can fix it

**Comment by dohinafs** [comment]
I think #23 addresses this issue. Let me know if you're doing any different improvements and I'll assign it to you.

**Comment by prvn-kumar01** [comment]
@dohinafs Assign me #23

**Comment by dohinafs** [comment]
I cannot assign an issue assigned to another contributor to you. You can raise a different issue to contribute on.

**Comment by Pooja3Bhattrai** [comment]
@dohinafs would like to assign me this issue with hassle-free comunication?
