### ISSUE TITLE
Ice Cream Cards is not responsive in Small devices 

### ISSUE THREAD

**Issue by Hemraj-7** [dohinaf/basic-icecream-website#417]
Ice Cream Cards is not responsive in Small devices 
now website looking bad
but when we fix this issue website will be looking good

![Screenshot 2024-10-10 175346](https://github.com/user-attachments/assets/367d2ffe-155f-426c-baa7-596e13b47d0d)

I want to do this contribution 
assign me

**Comment by dohinafs** [comment]
https://arcticdelights.netlify.app/ this is the recent version of the website

**Comment by Hemraj-7** [comment]
> https://arcticdelights.netlify.app/ this is the recent version of the website

Latest version is looking good don't want to edit
