### ISSUE TITLE
Redirecting to social media pages

### ISSUE THREAD

**Issue by Yashwanth112004** [dohinaf/basic-icecream-website#421]
The social media icons in the footer are not working.
They are redirecting to the top of the page. 
I want to work on this issue. Provide me the links of all the social media pages, So that I can update it.
Please assign me this task and add labels - hacktoberfest-accepted, gssoc-ext, level 1/2/3

Best Regards,
Puligilla Yashwanth
Contributor

**Comment by dohinafs** [comment]
This is not possible as we do not have social media pages for this website.
