### ISSUE TITLE
Add brand logo

### ISSUE THREAD

**Issue by Shreya-0510** [dohinaf/basic-icecream-website#44]
Currently the logo is pretty basic and generic. I would like to add a good logo with brand name that is 'ArcticDelights'. This will highlight the brand and is very important for any website as it is the first thing that a user will notice
![image](https://github.com/user-attachments/assets/572df73b-1dfd-427c-bb2f-b6cc42632a6f)

**Comment by gouravi19** [comment]
Proposal for Logo Enhancement
I noticed that there’s already a logo design in place, but I’d love to contribute my own ideas. I believe I can offer a fresh perspective that aligns with the project’s vision. I’ve created a few concepts that I think could enhance the project’s identity.

If you’re open to it, I would appreciate the opportunity to share my designs and discuss them further.
