### ISSUE TITLE
Enhancing the menu section 

### ISSUE THREAD

**Issue by anushkas1704** [dohinaf/basic-icecream-website#458]
Hi i would like to fix the issue of the menu section to make the brand seem more welcoming and enhance the brand identity. i would change UI of the menu section to be more clean and aesthetic , as well as good to look at.

![Screenshot 2024-10-11 125347](https://github.com/user-attachments/assets/4e680a64-a7f3-441c-80cf-1a606821b44d)
Labels needed:
hactoberfest-accepted
gssoc-ext
level 2 or 3 
@dohinafs could you assign this issue to me ?

**Comment by dohinafs** [comment]
Refer to the updated version: arcticdelights.netlify.app
