### ISSUE TITLE
Add a Reviews/Testanomial Section Just Before the Footer

### ISSUE THREAD

**Issue by Sapta-Dev27** [dohinaf/basic-icecream-website#46]
Reviews Section :
Features 👍 : 
1. Testanomials from Users with their Photos
2. Ratings will also be shown in the Reviews Section
3. Scrollbar Animation Feature Will be Implemented 

I would like to work on this issue
Kindly assign me the issue @dohinafs !!

**Comment by Riddhi12349** [comment]
hi please assign me this issue
