### ISSUE TITLE
Password strength indicator

### ISSUE THREAD

**Issue by jvkousthub** [dohinaf/basic-icecream-website#467]
Add a password strength indicator that shows the password strength using colors like red orange green 
This is necessary for security

**Comment by jvkousthub** [comment]
@dohinafs I would like to work on this issue
I am a GSSoC and Hacktoberfest contributor

**Comment by jvkousthub** [comment]
@dohinafs please add level label #492

**Comment by SaanyaGarg5** [comment]
you can assign this task to me...

**Comment by jvkousthub** [comment]
Pr made at #492
