### ISSUE TITLE
Dark theme fonts color updation

### ISSUE THREAD

**Issue by saumyayadav25** [dohinaf/basic-icecream-website#468]
This selection of color theme is not looking good, and not even properly visible. The color should a little bright.
<img width="1377" alt="Screenshot 2024-10-11 at 6 03 29 PM" src="https://github.com/user-attachments/assets/2d89983e-c3ca-4bd2-8c97-660c185159fa">

also, while adding flavour, it's not visible what are you typing.
<img width="1358" alt="Screenshot 2024-10-11 at 6 04 27 PM" src="https://github.com/user-attachments/assets/cbb9191d-0729-4486-a95b-829f6aff95d4">

Please do let me know if this issue will be assigned to me.

**Comment by saumyayadav25** [comment]
@dohinafs kindly review this issue. 
Thanks!

**Comment by SaanyaGarg5** [comment]
you can assign this task to me...

**Comment by saumyayadav25** [comment]
> you can assign this task to me...

This issue has already been solved and merged.
