### ISSUE TITLE
BUG Add socials Links in the footer

### ISSUE THREAD

**Issue by akanksha1055** [dohinaf/basic-icecream-website#476]
![image](https://github.com/user-attachments/assets/cb892bc6-0c45-448c-b72f-33b28e9b30dc)

Currently as the social icons redirect to the home page only . I would like to add the correct social linksto the icons improving the interface .

please assign me this under GSSSOC and HACKTOBER

thankyouuu

**Comment by dohinafs** [comment]
We don't have social media pages for this website.

**Comment by akanksha1055** [comment]
should i simply add the links for the platforms shown in the icon ??

**Comment by dohinafs** [comment]
> should i simply add the links for the platforms shown in the icon ??

Sorry, I don't think that is necessary. You can raise another valid issue.
