### ISSUE TITLE
ENHANCEMENT: mobile responsiveness(hactoberfest)

### ISSUE THREAD

**Issue by MisbahAnsar** [dohinaf/basic-icecream-website#479]
The abous us section doesn;t looks good in the mobile view must be some css issue, and the cards section the cards from both sides aren't properly margined, i am ready to work on this.

https://github.com/user-attachments/assets/610a996c-0cce-4e85-b50e-97f00c3668e2

i am ready to work on this issue

**Comment by dohinafs** [comment]
Kindly view the website from here: https://arcticdelights.netlify.app/

**Comment by MisbahAnsar** [comment]
I viewed it already, checked in all the phones at my home, that section isn't responsive in any device for mobile 🙏
