### ISSUE TITLE
Positioning of Icons, search bar improve

### ISSUE THREAD

**Issue by Harshgupta88156** [dohinaf/basic-icecream-website#48]
![Screenshot 2024-10-02 015432](https://github.com/user-attachments/assets/20330716-a209-4894-8b68-0e1997cf0e8e)

 Icons positioning and new icons inclusion to be done.
 @dohinafs assign me this project will rectify it!!!

**Comment by Altair-05** [comment]
I’m assigning this issue to you. However, before raising a pull request, please include a comparison photo of the previous navbar alongside your newly created navbar. If your design is an improvement over the previous one, I will merge it!

**Comment by Harshgupta88156** [comment]
![Screenshot 2024-10-02 183522](https://github.com/user-attachments/assets/ab685154-3b46-4432-8e87-b9a372182c17)
okay i have done a menu section inclusion !! you can check it if you like should PR it!!

**Comment by Altair-05** [comment]
ok
