### ISSUE TITLE
To remove "lorem ipsum"  text and to provide correct description !

### ISSUE THREAD

**Issue by 2004pra** [dohinaf/basic-icecream-website#485]
As  you can see in the below image i provided your website still shows lorem ipsum text where you should provide a correct description
according to you website theme.
please assign me this task under gssocextd24, hacktober fest.
@dohinafs 
![Screenshot 2024-10-12 142102](https://github.com/user-attachments/assets/c1a40579-a0e4-471b-8945-37b69a65479f)

**Comment by dohinafs** [comment]
Refer to the website here:
https://arcticdelights.netlify.app/

**Comment by dohinafs** [comment]
I've submitted a request to the program manager to correct the link. We have already fixed this issue so I cannot make it valid or assign it to you.
