### ISSUE TITLE
build review page

### ISSUE THREAD

**Issue by rohitsharma2610** [dohinaf/basic-icecream-website#49]
![image](https://github.com/user-attachments/assets/97ecd8fd-9d83-4a9b-a730-284265843be8)
when i click on review button, there is no page for review so can i make this?

**Comment by rohitsharma2610** [comment]
i want to work on this please assign me. and add gssoc, level, hackotober label.

**Comment by dohinafs** [comment]
@rohitsharma2610 I think issue #3 already addresses this.

**Comment by rohitsharma2610** [comment]
okay.
