### ISSUE TITLE
Implementing Cart Functionality

### ISSUE THREAD

**Issue by t1nt1n-s0lv3r** [dohinaf/basic-icecream-website#5]
When we press on add to cart , it is not adding to the cart and we are not able to even modify the number of ice cream we want to buy

Please assign this issue to me 
This is my first time working on open source 
please assign it under gssoc 24 and hacktoberfest

**Comment by dohinafs** [comment]
@t1nt1n-s0lv3r When we press add to cart, it does add item to cart however we need to keep the cart open, else it is not visible. You can try to fix this issue along with the quantity modification issue. 

You have been assigned.

**Comment by Riddhi12349** [comment]
hi please assign me this issue
