### ISSUE TITLE
Implementation of Payment UI Flows After Checkout

### ISSUE THREAD

**Issue by Blessy-B-Sherin** [dohinaf/basic-icecream-website#57]
I noticed that the Arctic Delights ecommerce website currently lacks payment UI flows after the user clicks the checkout button. To enhance the purchasing experience, I propose to implement a comprehensive payment interface that includes the following features:

1. **Payment Method Selection:** 
   - Options for credit/debit cards, digital wallets (like PayPal), and cash on delivery.
  
2. **User Input Forms:** 
   - Fields for entering card details, billing address, and contact information.

3. **Order Summary:** 
   - A clear summary of the items being purchased, including quantities, prices, and total cost.

4. **Responsive Design:**
   - Ensuring the payment UI is mobile-friendly and works seamlessly across different devices.

**Comment by Divyansh2992** [comment]
Please assign it to me ,I want to contribute in it.

**Comment by dohinafs** [comment]
@Divyansh2992 Assignment is done in a first come first serve basis. Kindly raise your issue separately.
