### ISSUE TITLE
Feat : ADD A SEPARATE CART PAGE WHERE WE SEE OUR ADDED ITEMS 

### ISSUE THREAD

**Issue by AbhinaySngh** [dohinaf/basic-icecream-website#6]
![Screenshot 2024-10-01 192022](https://github.com/user-attachments/assets/f74f3054-14e8-4270-9d28-e6be97344f59)

**Comment by AbhinaySngh** [comment]
@dohinafs Please assign me this issue under GSSOC label.

**Comment by dohinafs** [comment]
@AbhinaySngh You have been assigned.

**Comment by dohinafs** [comment]
Are you still working on this issue?

**Comment by Sudhanshu248** [comment]
Please assign me this issue
