### ISSUE TITLE
Navbar poorly designed

### ISSUE THREAD

**Issue by NIKITABARANWAL890** [dohinaf/basic-icecream-website#629]
![Screenshot 2024-10-17 200622](https://github.com/user-attachments/assets/b96ffc19-1d59-424c-b31c-ec82dbca05b7)

I can make it's UI more better and visually appealing.

@dohinafs Kindly assign me this issue under GSSOC'24 ext.

**Comment by pagaredivyanka** [comment]
I noticed this issue hasn't been addressed yet. I'd like to work on it if that's okay.
