### ISSUE TITLE
Animations 

### ISSUE THREAD

**Issue by riyarane46** [dohinaf/basic-icecream-website#65]
@dohinaf , i would like to work on the animations of the page , 
i believe i can do this task as i have a strong hold over css styling .
please assign me this issue under gssoc24 and hactoberfest.

**Comment by Altair-05** [comment]
@riyarane46, please explain the changes briefly. You can also include screenshots or videos. Since others are already working on similar issues, what new contributions will you bring?

**Comment by riyarane46** [comment]
@dohinafs 
i would add a a smooth zoom-in or fade-in effect for the ice cream image when the page loads or when the user scrolls down to the image.
also the buttons does not look consistent when you hover 
at some places its expanding from right and in the menu section they are expanding from both left and right which doesnt look good i will fix that

**Comment by Altair-05** [comment]
Don't create similar issues repeatedly, as you've done with the animations and menu parts. Please consolidate them under the animations section

**Comment by riyarane46** [comment]
@Altair-05 
okay sorry . wont happen again.
can i start working on this issue??

**Comment by Altair-05** [comment]
@riyarane46  yes sure!

**Comment by riyarane46** [comment]
please can you also assign tags to my issue  under gssoc24 extd and hactoberfest

**Comment by riyarane46** [comment]
@dohinafs @Altair-05 
please add the tags of gssoc24 extd and hactoberfest

i have changed the button animation to imcrease in size a little and also added a border radius to make it visually appealing . sharper buttons dont look good . 
i have also added an animation to the about us section now whnever we scroll to the about us section it fades in from the left of the page making it attractive .

please add labels so that i can send you a pull request

**Comment by riyarane46** [comment]
@Altair-05 i have sent a pull request please review it
