### ISSUE TITLE
menu cards

### ISSUE THREAD

**Issue by riyarane46** [dohinaf/basic-icecream-website#66]
@dohinafs   
i want to enhance the menu cards styling to make it look more attractive
i believe i can do this task efficiently as i have a strong hold over css styling. 
could you please assign me this task under GSSoC24 extd and hactoberfest24.

**Comment by Altair-05** [comment]
@riyarane46, please explain the changes briefly. Also, make sure you’re not creating duplicate issues and avoid spamming

**Comment by riyarane46** [comment]
@dohinafs , 
i would add the following functionalities
On hover, the image of each ice cream can smoothly zoom in or out, drawing attention to the product.
