### ISSUE TITLE
Add Theme Changer Button for Dark Mode and Light Mode

### ISSUE THREAD

**Issue by Sujal1201** [dohinaf/basic-icecream-website#7]
Feature Request: Implement a theme changer button that allows users to toggle between dark mode and light mode using a checkbox.

Current Behavior: Currently, there is no option for users to switch between light and dark themes on the website.

Desired Behavior:

A checkbox should be added to the website header for toggling the theme.
When the checkbox is checked, the website should switch to dark mode.
When unchecked, the website should revert to light mode.
The user's preference should be saved using local storage so that the selected theme persists across sessions.
Proposed Solution:

Create a checkbox in the header for theme switching.
Use JavaScript to listen for changes on the checkbox and apply the corresponding theme.
Use local storage to save the user's theme preference and load it on page load.
Additional Notes:

Consider using CSS custom properties for easier theme management.
Ensure that the implementation is responsive and visually appealing.

**Comment by Sujal1201** [comment]
please assign me for this issue

**Comment by dohinafs** [comment]
@Sujal1201 You have been assigned.

**Comment by rounakdey6** [comment]
please assign this issue to me

**Comment by dohinafs** [comment]
@rounakdey6 Kindly raise a different issue separately. This issue has already been assigned.
