### ISSUE TITLE
Review and Blogs

### ISSUE THREAD

**Issue by 5hreyanshPandey** [dohinaf/basic-icecream-website#75]
I want to add review and blogs section in the website ,can you please assign me this issue.

**Comment by dohinafs** [comment]
@5hreyanshPandey These issues have already been raised by #3 and #4

**Comment by dohinafs** [comment]
@5hreyanshPandey You can ask the issue raiser if they're interested in collaborating with you else I cannot assign you to the same issue. You can raise other issues which haven't been solved yet.
