### ISSUE TITLE
Search button is not working 

### ISSUE THREAD

**Issue by devxMani** [dohinaf/basic-icecream-website#78]
![image](https://github.com/user-attachments/assets/48718c23-8e96-47d5-aff7-90f0b6999995)
can you assign this task to me and please add( GSoc level 3 ) and Hacktoberfest label

**Comment by dohinafs** [comment]
#43 raises the same issue.

**Comment by dohinafs** [comment]
No definite time limit yet. If the contributor is inactive and doesn't resolve it within 3-4 days, I can assign it to you.
