### ISSUE TITLE
Nav bar functionality and button issues

### ISSUE THREAD

**Issue by bvvivek6** [dohinaf/basic-icecream-website#82]
The nav bar does not indicate in which section i'm in. Its not highlighted I want to add that functionality and improve the experience.
Review section is missing. 
My order does not notify me.
If i click my order, it take me to the home page. Instead it should show me my cart.
Addition of light/dark mode

Kindly assign me this project to fix these issues and make the project more appealing

**Comment by sambedan1** [comment]
Review and fix any existing functionality issues in the navbar, ensuring all links direct users to the correct pages.
Enhance button functionality to ensure they respond appropriately to user actions, such as clicks and hovers.
Test the navbar and buttons across different devices and browsers to ensure consistent performance and responsiveness.
please assign this task to me

**Comment by dohinafs** [comment]
@bvvivek6 
Some of the issues you've mentioned have already been raised and assigned. You are assigned to the below issues:
My order does not notify me.
If i click my order, it take me to the home page. Instead it should show me my cart.

**Comment by dohinafs** [comment]
@sambedan1 The issues you've stated have already been raised. Kindly do not raise duplicate issues.
