### ISSUE TITLE
Can add new functionalities like Animation on scroll and Pleasing hovering effect 

### ISSUE THREAD

**Issue by Vijitverm1234** [dohinaf/basic-icecream-website#83]
- Adding some Hovering effect on card 
- Adding Animations on scroll

**Comment by sambedan1** [comment]
Implement smooth animations that trigger as users scroll down the page to highlight important content.
Add engaging hover effects to interactive elements for a more dynamic and visually appealing interface.
Ensure these features are optimized for performance across all devices to maintain fast loading times.
please assign this task to me

**Comment by dohinafs** [comment]
@Vijitverm1234 @sambedan1 The both of you wish to collaborate on the same issue?

**Comment by Vijitverm1234** [comment]
I am going to work on it , if anything left or you want more modification then @sambedan1 can surely modify or update it . it can act like collab of both of us but in different turns

**Comment by sambedan1** [comment]
I also intrested
