### ISSUE TITLE
improving ui on different devices

### ISSUE THREAD

**Issue by manoj-netizenn** [dohinaf/basic-icecream-website#85]
implementing the css to seamless experience on different devices like 
Tablets , android TVs and different screen sizes
under gssoc-ext

**Comment by dohinafs** [comment]
#23 already addresses this issue. Kindly don't raise duplicate issues.

**Comment by ishanguptaofficial** [comment]
Hello Dohinaf Team,

My name is Ishan, and I am a 4th-year BTech student with experience in full-stack development. I would love to contribute to your project. Here is my LinkedIn profile: https://www.linkedin.com/in/ishanguptaofficial/.

Could you please assign me to this issue? Looking forward to your response.

Best regards,
Ishan
