### ISSUE TITLE
Improve Menu section

### ISSUE THREAD

**Issue by isnehamondal** [dohinaf/basic-icecream-website#9]
I am Sneha Mondal, GSSoC'24 Extd.

ISSUE:
The our menu section looks quite unrealistic which might lead to customers being not that interested in buying unlike the home page which actually creates or makes the customer expect more from this.

![og issue](https://github.com/user-attachments/assets/9fbc17f2-9c86-4f09-ae5e-48249842c100)

WHAT I CAN DO?
I can improve this by adding more css features including changes its pictures size and design, the grid box or column, the font style and size of description and improve it overall. 

I request you to kindly assign this task to me.

**Comment by dohinafs** [comment]
@isnehamondal You have been assigned.

**Comment by vijaychandra1910** [comment]
Adding some hover effect in the our menu card

**Comment by dohinafs** [comment]
@vijaychandra1910 You have been assigned.

**Comment by isnehamondal** [comment]
Hello @dohinafs , I have made the changes that I have mentioned. I want to show it to you for review. Can you please help me with it? How do I make changes that it will reflect to you as well? I have cloned it and made the changes. Please tell me what shall I do now or shall I make a file of it like a ss or something and show you here?

**Comment by isnehamondal** [comment]
I have made the necessary changes, please do look into it. I have pulled request.
