### ISSUE TITLE
Add Quantity Selector for Add to Cart Feature

### ISSUE THREAD

**Issue by sriharsha0x1** [dohinaf/basic-icecream-website#90]
I propose adding an option to select the number of items before adding a product to the cart. This feature would enhance user convenience by allowing them to add multiple items at once, rather than repeating the process multiple times. I would like to work on implementing this feature. @dohinaf
Could you please assign me this work?
![image](https://github.com/user-attachments/assets/d6316b29-a81e-49e9-a232-6e5192d2003b)

for example:
![image](https://github.com/user-attachments/assets/a7485b4d-b505-49b2-b99e-280505678333)

**Comment by mdfarid01** [comment]
Can you assign this to me? It would be great to contribute to your project!! I'm in GSSoC24
