### ISSUE TITLE
Refactor CSS: Split large stylesheet into modular components for improved maintainability

### ISSUE THREAD

**Issue by Lonwwolf14** [dohinaf/basic-icecream-website#97]
Our current CSS file (style.css) has grown to nearly 1000 lines, making it difficult to maintain and navigate. To improve code organization, readability, and maintainability, we should consider splitting this large file into smaller, more focused stylesheets.

### Proposed changes:

Create separate CSS files for different concerns (e.g., variables, layout, components, sections, responsive styles, animations).
Implement a main CSS file that imports these modular stylesheets.
Update the HTML to reference only the main CSS file.

### This refactoring will:

Enhance code organization and readability
Improve maintainability by separating concerns
Make it easier for developers to locate and modify specific styles
Potentially improve performance through better caching of individual stylesheets

**Comment by Raehale** [comment]
I would like to work on this issue if possible. Thanks!

**Comment by dohinafs** [comment]
@Lonwwolf14 Are you interested in working on this issue?

**Comment by Lonwwolf14** [comment]
Yess

**Comment by Lonwwolf14** [comment]
Will you pls consider merging this issue because contributors are having really hard time to add the CSS
