### ISSUE TITLE
 Request for Blog Section Enhancement Task Assignment

### ISSUE THREAD

**Issue by shivamv003** [dohinaf/basic-icecream-website#99]
![image](https://github.com/user-attachments/assets/af82cb02-8804-4996-a55b-423b53051cc7)

 I have reviewed the current blog section of our project and noticed that it contains an overwhelming amount of text, which might negatively affect user experience. I believe that restructuring the page to be more professional, clean, and visually appealing will significantly enhance user engagement.

I would like to take the initiative to redesign the blog section to make it more organized, minimalistic, and user-friendly. 

Please consider assigning this task to me as part of my contributions under GSSoC.

**Comment by AbhinabPalei** [comment]
Please assign me this issue under GSSoC- ext

**Comment by shivamv003** [comment]
please assign me as i have raised this issue under the gssoc
